//Try- Tenta gerar um erro
//catch - mostra o erro

const x = 10;

try{
    x = 2
}catch(err){
    console.log(`Error: , ${err} `)
}